.TH "_REQUEST_TYPE" 3 "Sun Oct 17 2010" "Version 01" "Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_REQUEST_TYPE \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <usb.h>\fP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fB_BM\fP"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "__packed struct \fB_REQUEST_TYPE::_BM\fP \fBBM\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBB\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 46 of file usb.h.
.SH "Field Documentation"
.PP 
.SS "\fBBYTE\fP \fBB\fP"
.PP
Definition at line 52 of file usb.h.
.SS "__packed struct \fB_REQUEST_TYPE::_BM\fP  \fBBM\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware from the source code.
