.TH "_USB_DEVICE_QUALIFIER_DESCRIPTOR" 3 "Sun Oct 17 2010" "Version 01" "Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_USB_DEVICE_QUALIFIER_DESCRIPTOR \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <usb.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBbLength\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBbDescriptorType\fP"
.br
.ti -1c
.RI "\fBWORD\fP \fBbcdUSB\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBbDeviceClass\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBbDeviceSubClass\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBbDeviceProtocol\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBbMaxPacketSize0\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBbNumConfigurations\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBbReserved\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 160 of file usb.h.
.SH "Field Documentation"
.PP 
.SS "\fBWORD\fP \fBbcdUSB\fP"
.PP
Definition at line 163 of file usb.h.
.SS "\fBBYTE\fP \fBbDescriptorType\fP"
.PP
Definition at line 162 of file usb.h.
.SS "\fBBYTE\fP \fBbDeviceClass\fP"
.PP
Definition at line 164 of file usb.h.
.SS "\fBBYTE\fP \fBbDeviceProtocol\fP"
.PP
Definition at line 166 of file usb.h.
.SS "\fBBYTE\fP \fBbDeviceSubClass\fP"
.PP
Definition at line 165 of file usb.h.
.SS "\fBBYTE\fP \fBbLength\fP"
.PP
Definition at line 161 of file usb.h.
.SS "\fBBYTE\fP \fBbMaxPacketSize0\fP"
.PP
Definition at line 167 of file usb.h.
.SS "\fBBYTE\fP \fBbNumConfigurations\fP"
.PP
Definition at line 168 of file usb.h.
.SS "\fBBYTE\fP \fBbReserved\fP"
.PP
Definition at line 169 of file usb.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware from the source code.
