.TH "_USB_EP_DATA" 3 "Sun Oct 17 2010" "Version 01" "Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_USB_EP_DATA \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <usbcore.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBBYTE\fP * \fBpData\fP"
.br
.ti -1c
.RI "\fBWORD\fP \fBCount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file usbcore.h.
.SH "Field Documentation"
.PP 
.SS "\fBWORD\fP \fBCount\fP"
.PP
Definition at line 23 of file usbcore.h.
.SS "\fBBYTE\fP* \fBpData\fP"
.PP
Definition at line 22 of file usbcore.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware from the source code.
