.TH "_USB_INTERFACE_DESCRIPTOR" 3 "Sun Oct 17 2010" "Version 01" "Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_USB_INTERFACE_DESCRIPTOR \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <usb.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBbLength\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBbDescriptorType\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBbInterfaceNumber\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBbAlternateSetting\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBbNumEndpoints\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBbInterfaceClass\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBbInterfaceSubClass\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBbInterfaceProtocol\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBiInterface\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 185 of file usb.h.
.SH "Field Documentation"
.PP 
.SS "\fBBYTE\fP \fBbAlternateSetting\fP"
.PP
Definition at line 189 of file usb.h.
.SS "\fBBYTE\fP \fBbDescriptorType\fP"
.PP
Definition at line 187 of file usb.h.
.SS "\fBBYTE\fP \fBbInterfaceClass\fP"
.PP
Definition at line 191 of file usb.h.
.SS "\fBBYTE\fP \fBbInterfaceNumber\fP"
.PP
Definition at line 188 of file usb.h.
.SS "\fBBYTE\fP \fBbInterfaceProtocol\fP"
.PP
Definition at line 193 of file usb.h.
.SS "\fBBYTE\fP \fBbInterfaceSubClass\fP"
.PP
Definition at line 192 of file usb.h.
.SS "\fBBYTE\fP \fBbLength\fP"
.PP
Definition at line 186 of file usb.h.
.SS "\fBBYTE\fP \fBbNumEndpoints\fP"
.PP
Definition at line 190 of file usb.h.
.SS "\fBBYTE\fP \fBiInterface\fP"
.PP
Definition at line 194 of file usb.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware from the source code.
