.TH "_USB_ENDPOINT_DESCRIPTOR" 3 "Sun Oct 17 2010" "Version 01" "Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_USB_ENDPOINT_DESCRIPTOR \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <usb.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBbLength\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBbDescriptorType\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBbEndpointAddress\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBbmAttributes\fP"
.br
.ti -1c
.RI "\fBWORD\fP \fBwMaxPacketSize\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBbInterval\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 198 of file usb.h.
.SH "Field Documentation"
.PP 
.SS "\fBBYTE\fP \fBbDescriptorType\fP"
.PP
Definition at line 200 of file usb.h.
.SS "\fBBYTE\fP \fBbEndpointAddress\fP"
.PP
Definition at line 201 of file usb.h.
.SS "\fBBYTE\fP \fBbInterval\fP"
.PP
Definition at line 204 of file usb.h.
.SS "\fBBYTE\fP \fBbLength\fP"
.PP
Definition at line 199 of file usb.h.
.SS "\fBBYTE\fP \fBbmAttributes\fP"
.PP
Definition at line 202 of file usb.h.
.SS "\fBWORD\fP \fBwMaxPacketSize\fP"
.PP
Definition at line 203 of file usb.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware from the source code.
