.TH "_USB_SETUP_PACKET" 3 "Sun Oct 17 2010" "Version 01" "Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_USB_SETUP_PACKET \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <usb.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBREQUEST_TYPE\fP \fBbmRequestType\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBbRequest\fP"
.br
.ti -1c
.RI "\fBWORD_BYTE\fP \fBwValue\fP"
.br
.ti -1c
.RI "\fBWORD_BYTE\fP \fBwIndex\fP"
.br
.ti -1c
.RI "\fBWORD\fP \fBwLength\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 78 of file usb.h.
.SH "Field Documentation"
.PP 
.SS "\fBREQUEST_TYPE\fP \fBbmRequestType\fP"
.PP
Definition at line 79 of file usb.h.
.SS "\fBBYTE\fP \fBbRequest\fP"
.PP
Definition at line 80 of file usb.h.
.SS "\fBWORD_BYTE\fP \fBwIndex\fP"
.PP
Definition at line 82 of file usb.h.
.SS "\fBWORD\fP \fBwLength\fP"
.PP
Definition at line 83 of file usb.h.
.SS "\fBWORD_BYTE\fP \fBwValue\fP"
.PP
Definition at line 81 of file usb.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware from the source code.
