.TH "_USB_STRING_DESCRIPTOR" 3 "Sun Oct 17 2010" "Version 01" "Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_USB_STRING_DESCRIPTOR \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <usb.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBbLength\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBbDescriptorType\fP"
.br
.ti -1c
.RI "\fBWORD\fP \fBbString\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 208 of file usb.h.
.SH "Field Documentation"
.PP 
.SS "\fBBYTE\fP \fBbDescriptorType\fP"
.PP
Definition at line 210 of file usb.h.
.SS "\fBBYTE\fP \fBbLength\fP"
.PP
Definition at line 209 of file usb.h.
.SS "\fBWORD\fP \fBbString\fP"
.PP
Definition at line 211 of file usb.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware from the source code.
