.TH "_USB_CONFIGURATION_DESCRIPTOR" 3 "Sun Oct 17 2010" "Version 01" "Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_USB_CONFIGURATION_DESCRIPTOR \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <usb.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBbLength\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBbDescriptorType\fP"
.br
.ti -1c
.RI "\fBWORD\fP \fBwTotalLength\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBbNumInterfaces\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBbConfigurationValue\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBiConfiguration\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBbmAttributes\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBbMaxPower\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 173 of file usb.h.
.SH "Field Documentation"
.PP 
.SS "\fBBYTE\fP \fBbConfigurationValue\fP"
.PP
Definition at line 178 of file usb.h.
.SS "\fBBYTE\fP \fBbDescriptorType\fP"
.PP
Definition at line 175 of file usb.h.
.SS "\fBBYTE\fP \fBbLength\fP"
.PP
Definition at line 174 of file usb.h.
.SS "\fBBYTE\fP \fBbmAttributes\fP"
.PP
Definition at line 180 of file usb.h.
.SS "\fBBYTE\fP \fBbMaxPower\fP"
.PP
Definition at line 181 of file usb.h.
.SS "\fBBYTE\fP \fBbNumInterfaces\fP"
.PP
Definition at line 177 of file usb.h.
.SS "\fBBYTE\fP \fBiConfiguration\fP"
.PP
Definition at line 179 of file usb.h.
.SS "\fBWORD\fP \fBwTotalLength\fP"
.PP
Definition at line 176 of file usb.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware from the source code.
