.TH "F:/MDBlue/CQ/NghienCuu/USBDongle/USBLPC/Release/Firmware/LCD.h" 3 "Sun Oct 17 2010" "Version 01" "Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/MDBlue/CQ/NghienCuu/USBDongle/USBLPC/Release/Firmware/LCD.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBlcd_init\fP (void)"
.br
.ti -1c
.RI "void \fBlcd_clear\fP (void)"
.br
.ti -1c
.RI "void \fBlcd_putchar\fP (char c)"
.br
.ti -1c
.RI "void \fBset_cursor\fP (unsigned char column, unsigned char line)"
.br
.ti -1c
.RI "void \fBlcd_print\fP (unsigned char const *string)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void lcd_clear (void)"
.PP
Definition at line 280 of file LCD_4bit.c.
.SS "void lcd_init (void)"
.PP
Definition at line 226 of file LCD_4bit.c.
.SS "void lcd_print (unsigned char const * string)"
.PP
Definition at line 293 of file LCD_4bit.c.
.SS "void lcd_putchar (char c)"
.PP
Definition at line 214 of file LCD_4bit.c.
.SS "void set_cursor (unsigned char column, unsigned char line)"
.PP
Definition at line 265 of file LCD_4bit.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware from the source code.
