.TH "F:/MDBlue/CQ/NghienCuu/USBDongle/USBLPC/Release/Firmware/type.h" 3 "Sun Oct 17 2010" "Version 01" "Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/MDBlue/CQ/NghienCuu/USBDongle/USBLPC/Release/Firmware/type.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBNULL\fP   ((void *)0)"
.br
.ti -1c
.RI "#define \fBFALSE\fP   (0)"
.br
.ti -1c
.RI "#define \fBTRUE\fP   (1)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned char \fBBYTE\fP"
.br
.ti -1c
.RI "typedef unsigned short \fBWORD\fP"
.br
.ti -1c
.RI "typedef unsigned long \fBDWORD\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBBOOL\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define FALSE   (0)"
.PP
Definition at line 10 of file type.h.
.SS "#define NULL   ((void *)0)"
.PP
Definition at line 6 of file type.h.
.SS "#define TRUE   (1)"
.PP
Definition at line 14 of file type.h.
.SH "Typedef Documentation"
.PP 
.SS "typedef unsigned int \fBBOOL\fP"
.PP
Definition at line 20 of file type.h.
.SS "typedef unsigned char \fBBYTE\fP"
.PP
Definition at line 17 of file type.h.
.SS "typedef unsigned long \fBDWORD\fP"
.PP
Definition at line 19 of file type.h.
.SS "typedef unsigned short \fBWORD\fP"
.PP
Definition at line 18 of file type.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware from the source code.
