.TH "F:/MDBlue/CQ/NghienCuu/USBDongle/USBLPC/Release/Firmware/usbcfg.h" 3 "Sun Oct 17 2010" "Version 01" "Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/MDBlue/CQ/NghienCuu/USBDongle/USBLPC/Release/Firmware/usbcfg.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBUSB_POWER\fP   0"
.br
.ti -1c
.RI "#define \fBUSB_IF_NUM\fP   4"
.br
.ti -1c
.RI "#define \fBUSB_EP_NUM\fP   32"
.br
.ti -1c
.RI "#define \fBUSB_MAX_PACKET0\fP   64"
.br
.ti -1c
.RI "#define \fBUSB_DMA\fP   0"
.br
.ti -1c
.RI "#define \fBUSB_DMA_EP\fP   0x00000000"
.br
.ti -1c
.RI "#define \fBUSB_POWER_EVENT\fP   0"
.br
.ti -1c
.RI "#define \fBUSB_RESET_EVENT\fP   1"
.br
.ti -1c
.RI "#define \fBUSB_SUSPEND_EVENT\fP   1"
.br
.ti -1c
.RI "#define \fBUSB_RESUME_EVENT\fP   1"
.br
.ti -1c
.RI "#define \fBUSB_WAKEUP_EVENT\fP   0"
.br
.ti -1c
.RI "#define \fBUSB_SOF_EVENT\fP   0"
.br
.ti -1c
.RI "#define \fBUSB_ERROR_EVENT\fP   0"
.br
.ti -1c
.RI "#define \fBUSB_EP_EVENT\fP   0x0005"
.br
.ti -1c
.RI "#define \fBUSB_CONFIGURE_EVENT\fP   1"
.br
.ti -1c
.RI "#define \fBUSB_INTERFACE_EVENT\fP   1"
.br
.ti -1c
.RI "#define \fBUSB_FEATURE_EVENT\fP   0"
.br
.ti -1c
.RI "#define \fBUSB_CLASS\fP   1"
.br
.ti -1c
.RI "#define \fBUSB_HID\fP   0"
.br
.ti -1c
.RI "#define \fBUSB_HID_IF_NUM\fP   0"
.br
.ti -1c
.RI "#define \fBUSB_MSC\fP   0"
.br
.ti -1c
.RI "#define \fBUSB_MSC_IF_NUM\fP   0"
.br
.ti -1c
.RI "#define \fBUSB_AUDIO\fP   0"
.br
.ti -1c
.RI "#define \fBUSB_ADC_CIF_NUM\fP   0"
.br
.ti -1c
.RI "#define \fBUSB_ADC_SIF1_NUM\fP   1"
.br
.ti -1c
.RI "#define \fBUSB_ADC_SIF2_NUM\fP   2"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define USB_ADC_CIF_NUM   0"
.PP
Definition at line 151 of file usbcfg.h.
.SS "#define USB_ADC_SIF1_NUM   1"
.PP
Definition at line 152 of file usbcfg.h.
.SS "#define USB_ADC_SIF2_NUM   2"
.PP
Definition at line 153 of file usbcfg.h.
.SS "#define USB_AUDIO   0"
.PP
Definition at line 150 of file usbcfg.h.
.SS "#define USB_CLASS   1"
.PP
Definition at line 145 of file usbcfg.h.
.SS "#define USB_CONFIGURE_EVENT   1"
.PP
Definition at line 124 of file usbcfg.h.
.SS "#define USB_DMA   0"
.PP
Definition at line 75 of file usbcfg.h.
.SS "#define USB_DMA_EP   0x00000000"
.PP
Definition at line 76 of file usbcfg.h.
.SS "#define USB_EP_EVENT   0x0005"
.PP
Definition at line 123 of file usbcfg.h.
.SS "#define USB_EP_NUM   32"
.PP
Definition at line 73 of file usbcfg.h.
.SS "#define USB_ERROR_EVENT   0"
.PP
Definition at line 122 of file usbcfg.h.
.SS "#define USB_FEATURE_EVENT   0"
.PP
Definition at line 126 of file usbcfg.h.
.SS "#define USB_HID   0"
.PP
Definition at line 146 of file usbcfg.h.
.SS "#define USB_HID_IF_NUM   0"
.PP
Definition at line 147 of file usbcfg.h.
.SS "#define USB_IF_NUM   4"
.PP
Definition at line 72 of file usbcfg.h.
.SS "#define USB_INTERFACE_EVENT   1"
.PP
Definition at line 125 of file usbcfg.h.
.SS "#define USB_MAX_PACKET0   64"
.PP
Definition at line 74 of file usbcfg.h.
.SS "#define USB_MSC   0"
.PP
Definition at line 148 of file usbcfg.h.
.SS "#define USB_MSC_IF_NUM   0"
.PP
Definition at line 149 of file usbcfg.h.
.SS "#define USB_POWER   0"
.PP
Definition at line 71 of file usbcfg.h.
.SS "#define USB_POWER_EVENT   0"
.PP
Definition at line 116 of file usbcfg.h.
.SS "#define USB_RESET_EVENT   1"
.PP
Definition at line 117 of file usbcfg.h.
.SS "#define USB_RESUME_EVENT   1"
.PP
Definition at line 119 of file usbcfg.h.
.SS "#define USB_SOF_EVENT   0"
.PP
Definition at line 121 of file usbcfg.h.
.SS "#define USB_SUSPEND_EVENT   1"
.PP
Definition at line 118 of file usbcfg.h.
.SS "#define USB_WAKEUP_EVENT   0"
.PP
Definition at line 120 of file usbcfg.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware from the source code.
