LCD.h
void lcd_init(void)
References LCD_ALL_DIR_OUT, lcd_putchar, LCD_RS, lcd_write_4bit, lcd_write_cmd, UserFont.
Referenced by main.
void lcd_clear(void)
References lcd_write_cmd, set_cursor.
Referenced by main, VendorSetupStage.
void lcd_putchar(char c)
Referenced by lcd_init, lcd_print.
void set_cursor(unsigned char column, unsigned char line)
References lcd_write_cmd.
Referenced by lcd_clear, LCD_print, main.
void lcd_print(unsigned char const *string)
References lcd_putchar.
Referenced by LCD_print, main.