SerialLogger.h
MAX_LEN
Referenced by PLogNum.
NULL
Referenced by sendstring, USB_StatusInStage.
void init_serial(void)
References UxDLL, UxDLM, UxFDR, UxLCR.
Referenced by main.
int sendchar(int ch)
References UxLSR, UxTHR.
Referenced by getnumber, getstring, newline, sendstring.
int getkey(void)
References UxLSR, UxRBR.
Referenced by getnumber, getstring.
void newline(void)
References sendchar.
Referenced by main, PLog.
void sendstring(char *str)
References NULL, sendchar.
Referenced by PLog, PLogN, PLogNum.
void getstring(char *str, int size)
References getkey, sendchar.
int getnumber(void)
References getkey, sendchar.
void PLog(char *str)
References newline, sendstring, USE_SERIAL_LOGGER.
Referenced by main, USB_Init, VendorDataStage.
void PLogN(char *str)
References sendstring, USE_SERIAL_LOGGER.
Referenced by VendorDataStage.
void PLogNum(int num)
References itoa, MAX_LEN, sendstring, USE_SERIAL_LOGGER.
Referenced by VendorDataStage.
void reverse(char s[])
Referenced by itoa.
void itoa(int n, char s[])
References reverse.
Referenced by PLogNum.