VendorProcess.c
BYTE BulkBuf[MAX_PACKET][MAX_PACKET]
Referenced by Bulk2In, Bulk2Out.
BYTE BulkLen
Referenced by Bulk2In, Bulk2Out, VendorDataStage.
BYTE BufferMemory[512][512]
Referenced by Bulk2Out, LCD_print, VendorSetupStage.
BYTE MemoryLen
Referenced by Bulk2Out, VendorSetupStage.
unsigned char LCD_Buffer[17][17]
Referenced by LCD_print.
BYTE LED_status
Referenced by VendorDataStage.
int iSongSize[3][3]
unsigned char song_custom[256][256]
Referenced by NhacCustom.
int volume
Referenced by ChayNhac, VendorDataStage, VendorSetupStage.
void Bulk2Out(void)
References BufferMemory, BULK_EP_OUT, BulkBuf, BulkLen, MemoryLen, USB_ReadEP.
Referenced by USB_EndPoint2.
void Bulk2In(void)
References BULK_EP_IN, BulkBuf, BulkLen, USB_WriteEP.
Referenced by USB_EndPoint2.
void LCD_print()
References BufferMemory, LCD_Buffer, lcd_print, set_cursor.
Referenced by VendorDataStage, VendorSetupStage.
BOOL VendorSetupStage(USB_SETUP_PACKET *p)
References BufferMemory, _USB_EP_DATA::Count, EP0Data, FALSE, lcd_clear, LCD_print, MemoryLen, NhacCustom, NhacOff, NhacOn, _USB_EP_DATA::pData, TRUE, USB_DataInStage, USB_StatusInStage, VC_DAC_MUSIC1, VC_DAC_MUSIC2, VC_DAC_MUSIC_BY_DATA, VC_DAC_SET_VOLUME, VC_DAC_STOP_MUSIC, VC_GET_LIGHT_BAR, VC_LCD_CLEAR, VC_LCD_SET_TEXT, VC_LCD_SET_TEXT_NO_DATA, VC_SET_LIGHT_BAR, volume.
Referenced by USB_EndPoint0.
void VendorDataStage(USB_SETUP_PACKET *p)
References BulkLen, EP0Data, LCD_print, LED_status, _USB_EP_DATA::pData, PLog, PLogN, PLogNum, USB_StatusInStage, VC_DAC_SET_VOLUME, VC_LCD_SET_TEXT, VC_SET_LIGHT_BAR, volume.
Referenced by USB_EndPoint0.