usbcore.h
typedef struct _USB_EP_DATA USB_EP_DATA
WORD USB_DeviceStatus
Referenced by USB_GetStatus, USB_ResetCore, USB_SetClrFeature, USB_SetConfiguration, USB_WakeUp.
BYTE USB_DeviceAddress
Referenced by USB_EndPoint0, USB_ResetCore.
BYTE USB_Configuration
Referenced by USB_Configure_Event, USB_EndPoint0, USB_GetStatus, USB_ResetCore, USB_SetClrFeature, USB_SetConfiguration, USB_SetInterface.
DWORD USB_EndPointMask
Referenced by USB_GetStatus, USB_ResetCore, USB_SetClrFeature, USB_SetConfiguration, USB_SetInterface.
DWORD USB_EndPointHalt
Referenced by USB_GetStatus, USB_ResetCore, USB_SetClrFeature, USB_SetConfiguration, USB_SetInterface.
BYTE USB_AltSetting[USB_IF_NUM][USB_IF_NUM]
Referenced by USB_EndPoint0, USB_SetConfiguration, USB_SetInterface.
BYTE EP0Buf[USB_MAX_PACKET0][USB_MAX_PACKET0]
Referenced by USB_GetStatus, USB_StatusOutStage.
USB_EP_DATA EP0Data
Referenced by VendorDataStage, VendorSetupStage.
USB_SETUP_PACKET SetupPacket
Referenced by USB_EndPoint0, USB_GetDescriptor, USB_GetStatus, USB_SetClrFeature, USB_SetConfiguration, USB_SetInterface, USB_SetupStage.
void USB_ResetCore(void)
References USB_Configuration, USB_DeviceAddress, USB_DeviceStatus, USB_EndPointHalt, USB_EndPointMask, USB_POWER.
Referenced by USB_Reset_Event.
void USB_StatusInStage(void)
References NULL, USB_WriteEP.
Referenced by USB_EndPoint0, VendorDataStage, VendorSetupStage.
void USB_StatusOutStage(void)
References EP0Buf, USB_ReadEP.
Referenced by USB_EndPoint0.
void USB_DataInStage(void)
References _USB_EP_DATA::Count, _USB_EP_DATA::pData, USB_MAX_PACKET0, USB_WriteEP.
Referenced by USB_EndPoint0, USB_GetDescriptor, USB_GetStatus, VendorSetupStage.
void USB_DataOutStage(void)
References _USB_EP_DATA::Count, _USB_EP_DATA::pData, USB_ReadEP.
Referenced by USB_EndPoint0.