usbhw.c
EP_MSK_CTRL
EP_MSK_BULK
EP_MSK_INT
EP_MSK_ISO
Referenced by USB_ReadEP.
DWORD EPAdr(DWORD EPNum)
Referenced by USB_ClrStallEP, USB_ConfigEP, USB_DisableEP, USB_EnableEP, USB_ReadEP, USB_ResetEP, USB_SetStallEP, USB_WriteEP.
void WrCmd(DWORD cmd)
References CCEMTY_INT.
Referenced by USB_GetFrame, USB_ISR, USB_ReadEP, USB_WriteEP.
void WrCmdDat(DWORD cmd, DWORD val)
References CCEMTY_INT.
Referenced by USB_ClrStallEP, USB_Configure, USB_Connect, USB_DisableEP, USB_EnableEP, USB_ResetEP, USB_SetAddress, USB_SetStallEP, USB_WakeUp.
DWORD RdCmdDat(DWORD cmd)
References CCEMTY_INT, CDFULL_INT.
Referenced by USB_GetFrame, USB_ISR.
void USB_Init(void)
References PLog, USB_ISR, USB_Reset, USB_SetAddress.
Referenced by main.
void USB_Connect(BOOL con)
References CMD_SET_DEV_STAT, DAT_WR_BYTE, DEV_CON, WrCmdDat.
Referenced by main.
void USB_Reset(void)
References DEV_STAT_INT, EP_RLZED_INT, EP_SLOW_INT, ERR_INT, FRAME_INT, USB_ERROR_EVENT, USB_MAX_PACKET0, USB_SOF_EVENT.
Referenced by USB_Init, USB_ISR.
void USB_Suspend(void)
Referenced by USB_ISR.
void USB_Resume(void)
Referenced by USB_ISR.
void USB_WakeUp(void)
References CMD_SET_DEV_STAT, DAT_WR_BYTE, DEV_CON, USB_DeviceStatus, USB_GETSTATUS_REMOTE_WAKEUP, WrCmdDat.
void USB_WakeUpCfg(BOOL cfg)
Referenced by USB_SetClrFeature.
void USB_SetAddress(DWORD adr)
References CMD_SET_ADDR, DAT_WR_BYTE, DEV_EN, WrCmdDat.
Referenced by USB_EndPoint0, USB_Init.
void USB_Configure(BOOL cfg)
References CMD_CFG_DEV, CONF_DVICE, DAT_WR_BYTE, EP_RLZED_INT, WrCmdDat.
Referenced by USB_SetConfiguration.
void USB_ConfigEP(USB_ENDPOINT_DESCRIPTOR *pEPD)
References EP_RLZED_INT, EPAdr.
Referenced by USB_SetConfiguration, USB_SetInterface.
void USB_DirCtrlEP(DWORD dir)
Referenced by USB_EndPoint0.
void USB_EnableEP(DWORD EPNum)
References CMD_SET_EP_STAT, DAT_WR_BYTE, EPAdr, WrCmdDat.
Referenced by USB_SetConfiguration, USB_SetInterface.
void USB_DisableEP(DWORD EPNum)
References CMD_SET_EP_STAT, DAT_WR_BYTE, EP_STAT_DA, EPAdr, WrCmdDat.
Referenced by USB_SetConfiguration, USB_SetInterface.
void USB_ResetEP(DWORD EPNum)
References CMD_SET_EP_STAT, DAT_WR_BYTE, EPAdr, WrCmdDat.
Referenced by USB_SetConfiguration, USB_SetInterface.
void USB_SetStallEP(DWORD EPNum)
References CMD_SET_EP_STAT, DAT_WR_BYTE, EP_STAT_ST, EPAdr, WrCmdDat.
Referenced by USB_EndPoint0, USB_SetClrFeature.
void USB_ClrStallEP(DWORD EPNum)
References CMD_SET_EP_STAT, DAT_WR_BYTE, EPAdr, WrCmdDat.
Referenced by USB_EndPoint0, USB_SetClrFeature.
DWORD USB_ReadEP(DWORD EPNum, BYTE *pData)
References CMD_CLR_BUF, CMD_SEL_EP, CTRL_RD_EN, EP_MSK_ISO, EPAdr, PKT_LNGTH_MASK, PKT_RDY, WrCmd.
Referenced by Bulk2Out, USB_DataOutStage, USB_SetupStage, USB_StatusOutStage.
DWORD USB_WriteEP(DWORD EPNum, BYTE *pData, DWORD cnt)
References CMD_SEL_EP, CMD_VALID_BUF, CTRL_WR_EN, EPAdr, WrCmd.
Referenced by Bulk2In, USB_DataInStage, USB_StatusInStage.
DWORD USB_GetFrame(void)
References CMD_RD_FRAME, DAT_RD_FRAME, RdCmdDat, WrCmd.
void USB_ISR(void)
References CDFULL_INT, CMD_GET_DEV_STAT, CMD_RD_ERR_STAT, DAT_GET_DEV_STAT, DAT_RD_ERR_STAT, DEV_CON, DEV_CON_CH, DEV_RST, DEV_STAT_INT, DEV_SUS, DEV_SUS_CH, EP_SEL_STP, EP_SLOW_INT, ERR_INT, FRAME_INT, RdCmdDat, USB_EP_NUM, USB_Error_Event, USB_EVT_IN, USB_EVT_OUT, USB_EVT_SETUP, USB_P_EP, USB_Power_Event, USB_Reset, USB_Reset_Event, USB_Resume, USB_Resume_Event, USB_SOF_Event, USB_Suspend, USB_Suspend_Event, WrCmd.
Referenced by USB_Init.