usbuser.c
P_EP
void(* const USB_P_EP[16])(DWORD event)[16])(DWORD event)
Referenced by USB_ISR.
void USB_Reset_Event(void)
References LED_CFG, USB_ResetCore.
Referenced by USB_ISR.
void USB_Suspend_Event(void)
References LED_SUSP.
Referenced by USB_ISR.
void USB_Resume_Event(void)
References LED_SUSP.
Referenced by USB_ISR.
void USB_Configure_Event(void)
References LED_CFG, USB_Configuration.
Referenced by USB_EndPoint0.
void USB_Interface_Event(void)
Referenced by USB_EndPoint0.
void USB_EndPoint1(DWORD event)
void USB_EndPoint2(DWORD event)
References Bulk2In, Bulk2Out, USB_EVT_IN, USB_EVT_OUT.
void USB_EndPoint3(DWORD event)
void USB_EndPoint4(DWORD event)
void USB_EndPoint5(DWORD event)
void USB_EndPoint6(DWORD event)
void USB_EndPoint7(DWORD event)
void USB_EndPoint8(DWORD event)
void USB_EndPoint9(DWORD event)
void USB_EndPoint10(DWORD event)
void USB_EndPoint11(DWORD event)
void USB_EndPoint12(DWORD event)
void USB_EndPoint13(DWORD event)
void USB_EndPoint14(DWORD event)
void USB_EndPoint15(DWORD event)