usbuser.h
USB_EVT_SETUP
Referenced by USB_EndPoint0, USB_ISR.
USB_EVT_OUT
Referenced by USB_EndPoint0, USB_EndPoint2, USB_ISR.
USB_EVT_IN
Referenced by USB_EndPoint0, USB_EndPoint2, USB_ISR.
USB_EVT_OUT_NAK
USB_EVT_IN_NAK
USB_EVT_OUT_STALL
Referenced by USB_EndPoint0.
USB_EVT_IN_STALL
Referenced by USB_EndPoint0.
USB_EVT_OUT_DMA_EOT
USB_EVT_IN_DMA_EOT
USB_EVT_OUT_DMA_NDR
USB_EVT_IN_DMA_NDR
USB_EVT_OUT_DMA_ERR
USB_EVT_IN_DMA_ERR
void(* const USB_P_EP[16])(DWORD event)[16])(DWORD event)
Referenced by USB_ISR.
void USB_Power_Event(BOOL power)
Referenced by USB_ISR.
void USB_Reset_Event(void)
References LED_CFG, USB_ResetCore.
Referenced by USB_ISR.
void USB_Suspend_Event(void)
References LED_SUSP.
Referenced by USB_ISR.
void USB_Resume_Event(void)
References LED_SUSP.
Referenced by USB_ISR.
void USB_WakeUp_Event(void)
void USB_SOF_Event(void)
Referenced by USB_ISR.
void USB_Error_Event(DWORD error)
Referenced by USB_ISR.
void USB_EndPoint0(DWORD event)
References _USB_EP_DATA::Count, _USB_EP_DATA::pData, REQUEST_CLASS, REQUEST_STANDARD, REQUEST_TO_DEVICE, REQUEST_TO_INTERFACE, REQUEST_VENDOR, SetupPacket, USB_AltSetting, USB_ClrStallEP, USB_Configuration, USB_Configure_Event, USB_DataInStage, USB_DataOutStage, USB_DeviceAddress, USB_DirCtrlEP, USB_EVT_IN, USB_EVT_IN_STALL, USB_EVT_OUT, USB_EVT_OUT_STALL, USB_EVT_SETUP, USB_Feature_Event, USB_GetDescriptor, USB_GetStatus, USB_Interface_Event, USB_NumInterfaces, USB_REQUEST_CLEAR_FEATURE, USB_REQUEST_GET_CONFIGURATION, USB_REQUEST_GET_DESCRIPTOR, USB_REQUEST_GET_INTERFACE, USB_REQUEST_GET_STATUS, USB_REQUEST_SET_ADDRESS, USB_REQUEST_SET_CONFIGURATION, USB_REQUEST_SET_DESCRIPTOR, USB_REQUEST_SET_FEATURE, USB_REQUEST_SET_INTERFACE, USB_SetAddress, USB_SetClrFeature, USB_SetConfiguration, USB_SetInterface, USB_SetStallEP, USB_SetupStage, USB_StatusInStage, USB_StatusOutStage, VendorDataStage, VendorSetupStage.
void USB_EndPoint1(DWORD event)
void USB_EndPoint2(DWORD event)
References Bulk2In, Bulk2Out, USB_EVT_IN, USB_EVT_OUT.
void USB_EndPoint3(DWORD event)
void USB_EndPoint4(DWORD event)
void USB_EndPoint5(DWORD event)
void USB_EndPoint6(DWORD event)
void USB_EndPoint7(DWORD event)
void USB_EndPoint8(DWORD event)
void USB_EndPoint9(DWORD event)
void USB_EndPoint10(DWORD event)
void USB_EndPoint11(DWORD event)
void USB_EndPoint12(DWORD event)
void USB_EndPoint13(DWORD event)
void USB_EndPoint14(DWORD event)
void USB_EndPoint15(DWORD event)
void USB_Configure_Event(void)
References LED_CFG, USB_Configuration.
Referenced by USB_EndPoint0.
void USB_Interface_Event(void)
Referenced by USB_EndPoint0.
void USB_Feature_Event(void)
Referenced by USB_EndPoint0.