document.write('\n');
document.write('<HEAD> \n');
document.write('<TITLE></TITLE>\n');
document.write('</HEAD>\n');
document.write('<NOSCRIPT><a  href="http://ads.link.valueclick.net/redirect?host=h0005647&size=468x60&t=js&c=00&target_id=0&hcat=I11859&aid=I11859&pid=10.1007/978-3-540-69429-8_7&banner=a0134378&vcurlpreserve=http://www.springer.com" TARGET="_blank">\n');
document.write('<IMG SRC="http://cdn.valueclick.net/hg/0134/a0134378/a0134378.jpg" WIDTH="468" HEIGHT="60" BORDER="0"></a>\n');
document.write('</NOSCRIPT>\n');
document.write('<SCRIPT LANGUAGE=JavaScript>\n');
document.write('<!--\n');
document.write('var flashName	= "http://cdn.valueclick.net/hg/0134/a0134378/a0134378.swf";\n');
document.write('var altImgName	= "http://cdn.valueclick.net/hg/0134/a0134378/a0134378.jpg";\n');
document.write('var minFlashVer	= 5;\n');
document.write('var width = 468;\n');
document.write('var height = 60;\n');
document.write('var clickTAG = "http://ads.link.valueclick.net/redirect?host=h0005647;size=468x60;t=js;c=00;target_id=0;hcat=I11859;aid=I11859;pid=10.1007/978-3-540-69429-8_7;banner=a0134378;vcurlpreserve=http://www.springer.com/?cm_mmc%3DMediaplex-_-Mediaplex_Custom_Banner-_-BIO845-_-Koechel_springer.com_campaign_SL_Feb10";\n');
document.write('var gifclickTAG = "http://ads.link.valueclick.net/redirect?host=h0005647;size=468x60;t=js;c=00;target_id=0;hcat=I11859;aid=I11859;pid=10.1007/978-3-540-69429-8_7;banner=a0134378;vcurlpreserve=http://www.springer.com";\n');
document.write('var plugin = 0;\n');
document.write('var d = document;\n');
document.write('if (navigator.mimeTypes && navigator.mimeTypes["application/x-shockwave-flash"] && navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin) {\n');
document.write('	if (navigator.plugins && navigator.plugins["Shockwave Flash"])\n');
document.write('                var swver = (navigator.plugins["Shockwave Flash"].description.split( " " ))[2];\n');
document.write('		if (swver >= minFlashVer)\n');
document.write('			plugin = 1;\n');
document.write('}\n');
document.write('else if (navigator.userAgent && navigator.userAgent.indexOf("MSIE")>=0\n');
document.write('   && (navigator.userAgent.indexOf("Windows")>=0)) {\n');
document.write('	d.write("<SCR" + "IPT LANGUAGE=VBScript>");\n');
document.write('	d.write(\'on error resume next \');\n');
document.write('	d.write(unescape("%0A"));\n');
document.write('	d.write(\'if ( minFlashVer = 3 ) then plugin = ( IsObject(CreateObject("ShockwaveFlash.ShockwaveFlash.3")))\');\n');
document.write('	d.write(unescape("%0A"));\n');
document.write('	d.write(\'if (( minFlashVer <= 4) and (plugin <= 0 )) then plugin = ( IsObject(CreateObject("ShockwaveFlash.ShockwaveFlash.4")))\');\n');
document.write('	d.write(unescape("%0A"));\n');
document.write('	d.write(\'if (( minFlashVer <= 5) and (plugin <= 0 )) then plugin = ( IsObject(CreateObject("ShockwaveFlash.ShockwaveFlash.5")))\');\n');
document.write('	d.write(unescape("%0A"));\n');
document.write('	d.write(\'if (( minFlashVer <= 6) and (plugin <= 0 )) then plugin = ( IsObject(CreateObject("ShockwaveFlash.ShockwaveFlash.6")))\');\n');
document.write('	d.write(unescape("%0A"));\n');
document.write('	d.write(\'if (( minFlashVer <= 7) and (plugin <= 0 )) then plugin = ( IsObject(CreateObject("ShockwaveFlash.ShockwaveFlash.7")))\');\n');
document.write('	d.write(unescape("%0A"));\n');
document.write('	d.write(\'if (( minFlashVer <= 8) and (plugin <= 0 )) then plugin = ( IsObject(CreateObject("ShockwaveFlash.ShockwaveFlash.8")))\');\n');
document.write('	d.write(unescape("%0A"));\n');
document.write('	d.write(\'if (( minFlashVer <= 9) and (plugin <= 0 )) then plugin = ( IsObject(CreateObject("ShockwaveFlash.ShockwaveFlash.9")))\');\n');
document.write('	d.write(unescape("%0A"));\n');
document.write('	d.write(\'if (( minFlashVer <= 10) and (plugin <= 0 )) then plugin = ( IsObject(CreateObject("ShockwaveFlash.ShockwaveFlash.10")))\');\n');
document.write('	d.write("</SCR"+"IPT> ");\n');
document.write('}\n');
document.write('if ( plugin ) {\n');
document.write('	d.write(\'<OBJECT id="vc-34714-1278992763-4475" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"\');\n');
document.write('	d.write(\'  codebase="" \');\n');
document.write('	d.write(\' ID=movie WIDTH=\'+width+\' HEIGHT=\'+height+\'>\');\n');
document.write('	d.write(\' <PARAM NAME=movie VALUE="\'+flashName+\'?clickTAG=\'+clickTAG+\'"> <PARAM NAME=quality VALUE=high>\');\n');
document.write('	d.write(\' <PARAM name="wmode" value="window">\');\n');
document.write('	d.write(\' <EMBED src="\'+flashName+\'?clickTAG=\'+clickTAG+\'" quality=high wmode="window"\');\n');
document.write('	d.write(\' swLiveConnect=FALSE WIDTH=\'+width+\' HEIGHT=\'+height);\n');
document.write('	d.write(\' TYPE="application/x-shockwave-flash" PLUGINSPAGE="">\');\n');
document.write('	d.write(\' </EMBED>\');\n');
document.write('	d.write(\' </OBJECT>\');\n');
document.write('} else if (!(navigator.appName && navigator.appName.indexOf("Netscape")>=0 && navigator.appVersion.indexOf("2.")>=0)){\n');
document.write('	d.write(\'<a href="\'+gifclickTAG+\'" TARGET="_new">\');\n');
document.write('	d.write(\'<IMG SRC="\'+altImgName+\'" WIDTH=\'+width+\' HEIGHT=\'+height+\' BORDER="0"></a>\');\n');
document.write('}\n');
document.write('//-->\n');
document.write('\n');
document.write('    var EOLASloaded = 0;\n');
document.write('    function loadEOLAS() {\n');
document.write('        if( EOLASloaded == 1 ) { vc_obj_refresh("vc-34714-1278992763-4475"); } else { setTimeout( "loadEOLAS();", 5 ); }\n');
document.write('    }\n');
document.write('    loadEOLAS();\n');
document.write('</SCRI' + 'PT>\n');
document.write('<script src="http://ads.link.valueclick.net/js/eolas_fix"></SCRI' + 'PT>\n');
document.write('\n');
document.write('</html>\n');
document.write('\n');
document.write('\n');
document.write('  \n');
