LCD_4bit.c
DELAY_2N
LineLen
NumLines
PIN_E
PIN_RW
PIN_RS
PINS_CTRL
PINS_DATA
LCD_E
Referenced by lcd_write_4bit.
LCD_RW
Referenced by lcd_write_4bit.
LCD_RS
Referenced by lcd_init, lcd_write_cmd.
LCD_DATA_IN
LCD_DATA_OUT
Referenced by lcd_write_4bit.
LCD_ALL_DIR_OUT
Referenced by lcd_init.
LCD_DATA_DIR_IN
LCD_DATA_DIR_OUT
const unsigned char UserFont[8][8][8][8]
Referenced by lcd_init.
static void delay(int cnt)
static unsigned char lcd_read_status(void)
static unsigned char wait_while_busy(void)
void lcd_write_4bit(unsigned char c)
References LCD_DATA_OUT, LCD_E, LCD_RW.
Referenced by lcd_init, lcd_write_cmd.
void lcd_write_cmd(unsigned char c)
References LCD_RS, lcd_write_4bit.
Referenced by lcd_clear, lcd_init, set_cursor.
static void lcd_write_data(unsigned char c)
void lcd_putchar(char c)
Referenced by lcd_init, lcd_print.
void lcd_init(void)
References LCD_ALL_DIR_OUT, lcd_putchar, LCD_RS, lcd_write_4bit, lcd_write_cmd, UserFont.
Referenced by main.
void set_cursor(unsigned char column, unsigned char line)
References lcd_write_cmd.
Referenced by lcd_clear, LCD_print, main.
void lcd_clear(void)
References lcd_write_cmd, set_cursor.
Referenced by main, VendorSetupStage.
void lcd_print(unsigned char const *string)
References lcd_putchar.
Referenced by LCD_print, main.