Nhac.h
void InitSong(void)
References ChayNhac, song_joy, song_lamb.
Referenced by main.
void NhacOn(int iBaiHat)
References iPiano.
Referenced by NhacCustom, VendorSetupStage.
void NhacOff(void)
References iPiano.
Referenced by VendorSetupStage.
void NhacCustom(void *p, int iLen)
References NhacOn, song_custom.
Referenced by VendorSetupStage.