Nhac.c
freq_mult
Referenced by ChayNhac.
unsigned short sine_table256[][]
Referenced by ChayNhac.
unsigned long piano_Keys[][]
Referenced by ChayNhac.
unsigned char song_lamb[][]
Referenced by InitSong.
unsigned char song_joy[][]
Referenced by InitSong.
unsigned char song_custom[512][512]
Referenced by NhacCustom.
int volume
Referenced by ChayNhac, VendorDataStage, VendorSetupStage.
int accum
Referenced by ChayNhac.
int sample
Referenced by ChayNhac.
int freq
Referenced by ChayNhac.
int iPiano
Referenced by ChayNhac, NhacOff, NhacOn.
int iSizePiano
int count
unsigned char* song[][]
int iSongSize[3][3]
int iBaiHatA
Referenced by ChayNhac.
__irq void ChayNhac()
References accum, freq, freq_mult, iBaiHatA, iPiano, piano_Keys, sample, sine_table256, volume.
Referenced by InitSong.
void InitSong()
References ChayNhac, song_joy, song_lamb.
Referenced by main.
void NhacOn(int iBaiHat)
References iPiano.
Referenced by NhacCustom, VendorSetupStage.
void NhacOff(void)
References iPiano.
Referenced by VendorSetupStage.
void NhacCustom(void *p, int iLen)
References NhacOn, song_custom.
Referenced by VendorSetupStage.