SerialLogger.c
UART0
UxFDR
Referenced by init_serial.
UxLCR
Referenced by init_serial.
UxDLL
Referenced by init_serial.
UxDLM
Referenced by init_serial.
UxLSR
Referenced by getkey, sendchar.
UxTHR
Referenced by sendchar.
UxRBR
Referenced by getkey.
int USE_SERIAL_LOGGER
Referenced by PLog, PLogN, PLogNum.
void init_serial(void)
References UxDLL, UxDLM, UxFDR, UxLCR.
Referenced by main.
int sendchar(int ch)
References UxLSR, UxTHR.
Referenced by getnumber, getstring, newline, sendstring.
int getkey(void)
References UxLSR, UxRBR.
Referenced by getnumber, getstring.
void newline(void)
References sendchar.
Referenced by main, PLog.
void sendstring(char *str)
References NULL, sendchar.
Referenced by PLog, PLogN, PLogNum.
void getstring(char *str, int size)
References getkey, sendchar.
void reverse(char s[])
Referenced by itoa.
void itoa(int n, char s[])
References reverse.
Referenced by PLogNum.
int getnumber(void)
References getkey, sendchar.
void PLog(char *str)
References newline, sendstring, USE_SERIAL_LOGGER.
Referenced by main, USB_Init, VendorDataStage.
void PLogN(char *str)
References sendstring, USE_SERIAL_LOGGER.
Referenced by VendorDataStage.
void PLogNum(int num)
References itoa, MAX_LEN, sendstring, USE_SERIAL_LOGGER.
Referenced by VendorDataStage.