VendorProcess.h
MAX_PACKET
MAX_BULK_BUFFER
BULK_EP_IN
Referenced by Bulk2In.
BULK_EP_OUT
Referenced by Bulk2Out.
VC_LCD_CLEAR
Referenced by VendorSetupStage.
VC_LCD_SET_TEXT
Referenced by VendorDataStage, VendorSetupStage.
VC_DAC_MUSIC1
Referenced by VendorSetupStage.
VC_DAC_MUSIC2
Referenced by VendorSetupStage.
VC_DAC_MUSIC_BY_DATA
Referenced by VendorSetupStage.
VC_LCD_SET_TEXT_NO_DATA
Referenced by VendorSetupStage.
VC_GET_LIGHT_BAR
Referenced by VendorSetupStage.
VC_SET_LIGHT_BAR
Referenced by VendorDataStage, VendorSetupStage.
VC_DAC_STOP_MUSIC
Referenced by VendorSetupStage.
VC_DAC_SET_VOLUME
Referenced by VendorDataStage, VendorSetupStage.
void ReplyStatusLed(void)
void SetStatusLed(void)
void Bulk2Out(void)
References BufferMemory, BULK_EP_OUT, BulkBuf, BulkLen, MemoryLen, USB_ReadEP.
Referenced by USB_EndPoint2.
void Bulk2In(void)
References BULK_EP_IN, BulkBuf, BulkLen, USB_WriteEP.
Referenced by USB_EndPoint2.
BOOL VendorSetupStage(USB_SETUP_PACKET *p)
References BufferMemory, _USB_EP_DATA::Count, EP0Data, FALSE, lcd_clear, LCD_print, MemoryLen, NhacCustom, NhacOff, NhacOn, _USB_EP_DATA::pData, TRUE, USB_DataInStage, USB_StatusInStage, VC_DAC_MUSIC1, VC_DAC_MUSIC2, VC_DAC_MUSIC_BY_DATA, VC_DAC_SET_VOLUME, VC_DAC_STOP_MUSIC, VC_GET_LIGHT_BAR, VC_LCD_CLEAR, VC_LCD_SET_TEXT, VC_LCD_SET_TEXT_NO_DATA, VC_SET_LIGHT_BAR, volume.
Referenced by USB_EndPoint0.
void VendorDataStage(USB_SETUP_PACKET *p)
References BulkLen, EP0Data, LCD_print, LED_status, _USB_EP_DATA::pData, PLog, PLogN, PLogNum, USB_StatusInStage, VC_DAC_SET_VOLUME, VC_LCD_SET_TEXT, VC_SET_LIGHT_BAR, volume.
Referenced by USB_EndPoint0.
void VendorStatusInStage(USB_SETUP_PACKET *p)