usbcore.c
WORD USB_DeviceStatus
Referenced by USB_GetStatus, USB_ResetCore, USB_SetClrFeature, USB_SetConfiguration, USB_WakeUp.
BYTE USB_DeviceAddress
Referenced by USB_EndPoint0, USB_ResetCore.
BYTE USB_Configuration
Referenced by USB_Configure_Event, USB_EndPoint0, USB_GetStatus, USB_ResetCore, USB_SetClrFeature, USB_SetConfiguration, USB_SetInterface.
DWORD USB_EndPointMask
Referenced by USB_GetStatus, USB_ResetCore, USB_SetClrFeature, USB_SetConfiguration, USB_SetInterface.
DWORD USB_EndPointHalt
Referenced by USB_GetStatus, USB_ResetCore, USB_SetClrFeature, USB_SetConfiguration, USB_SetInterface.
BYTE USB_NumInterfaces
Referenced by USB_EndPoint0, USB_GetStatus, USB_SetConfiguration.
BYTE USB_AltSetting[USB_IF_NUM][USB_IF_NUM]
Referenced by USB_EndPoint0, USB_SetConfiguration, USB_SetInterface.
BYTE EP0Buf[USB_MAX_PACKET0][USB_MAX_PACKET0]
Referenced by USB_GetStatus, USB_StatusOutStage.
USB_EP_DATA EP0Data
Referenced by VendorDataStage, VendorSetupStage.
USB_SETUP_PACKET SetupPacket
Referenced by USB_EndPoint0, USB_GetDescriptor, USB_GetStatus, USB_SetClrFeature, USB_SetConfiguration, USB_SetInterface, USB_SetupStage.
void USB_ResetCore(void)
References USB_Configuration, USB_DeviceAddress, USB_DeviceStatus, USB_EndPointHalt, USB_EndPointMask, USB_POWER.
Referenced by USB_Reset_Event.
void USB_SetupStage(void)
References SetupPacket, USB_ReadEP.
Referenced by USB_EndPoint0.
void USB_DataInStage(void)
References _USB_EP_DATA::Count, _USB_EP_DATA::pData, USB_MAX_PACKET0, USB_WriteEP.
Referenced by USB_EndPoint0, USB_GetDescriptor, USB_GetStatus, VendorSetupStage.
void USB_DataOutStage(void)
References _USB_EP_DATA::Count, _USB_EP_DATA::pData, USB_ReadEP.
Referenced by USB_EndPoint0.
void USB_StatusInStage(void)
References NULL, USB_WriteEP.
Referenced by USB_EndPoint0, VendorDataStage, VendorSetupStage.
void USB_StatusOutStage(void)
References EP0Buf, USB_ReadEP.
Referenced by USB_EndPoint0.
__inline BOOL USB_GetStatus(void)
References EP0Buf, FALSE, _USB_EP_DATA::pData, REQUEST_TO_DEVICE, REQUEST_TO_ENDPOINT, REQUEST_TO_INTERFACE, SetupPacket, TRUE, USB_Configuration, USB_DataInStage, USB_DeviceStatus, USB_EndPointHalt, USB_EndPointMask, USB_NumInterfaces.
Referenced by USB_EndPoint0.
__inline BOOL USB_SetClrFeature(DWORD sc)
References FALSE, REQUEST_TO_DEVICE, REQUEST_TO_ENDPOINT, REQUEST_TO_INTERFACE, SetupPacket, TRUE, USB_ClrStallEP, USB_Configuration, USB_DeviceStatus, USB_EndPointHalt, USB_EndPointMask, USB_FEATURE_ENDPOINT_STALL, USB_FEATURE_REMOTE_WAKEUP, USB_GETSTATUS_REMOTE_WAKEUP, USB_SetStallEP, USB_WakeUpCfg.
Referenced by USB_EndPoint0.
__inline BOOL USB_GetDescriptor(void)
References _USB_EP_DATA::Count, FALSE, _USB_EP_DATA::pData, REQUEST_TO_DEVICE, REQUEST_TO_INTERFACE, SetupPacket, TRUE, USB_ConfigDescriptor, USB_CONFIGURATION_DESCRIPTOR_TYPE, USB_DataInStage, USB_DEVICE_DESC_SIZE, USB_DEVICE_DESCRIPTOR_TYPE, USB_DeviceDescriptor, USB_HID_IF_NUM, USB_STRING_DESCRIPTOR_TYPE, USB_StringDescriptor.
Referenced by USB_EndPoint0.
__inline BOOL USB_SetConfiguration(void)
References FALSE, SetupPacket, TRUE, USB_AltSetting, USB_CONFIG_SELF_POWERED, USB_ConfigDescriptor, USB_ConfigEP, USB_Configuration, USB_CONFIGURATION_DESCRIPTOR_TYPE, USB_Configure, USB_DeviceStatus, USB_DisableEP, USB_EnableEP, USB_ENDPOINT_DESCRIPTOR_TYPE, USB_EndPointHalt, USB_EndPointMask, USB_GETSTATUS_SELF_POWERED, USB_IF_NUM, USB_INTERFACE_DESCRIPTOR_TYPE, USB_NumInterfaces, USB_ResetEP.
Referenced by USB_EndPoint0.
__inline BOOL USB_SetInterface(void)
References FALSE, SetupPacket, TRUE, USB_AltSetting, USB_ConfigDescriptor, USB_ConfigEP, USB_Configuration, USB_CONFIGURATION_DESCRIPTOR_TYPE, USB_DisableEP, USB_EnableEP, USB_ENDPOINT_DESCRIPTOR_TYPE, USB_EndPointHalt, USB_EndPointMask, USB_INTERFACE_DESCRIPTOR_TYPE, USB_ResetEP.
Referenced by USB_EndPoint0.
void USB_EndPoint0(DWORD event)
References _USB_EP_DATA::Count, _USB_EP_DATA::pData, REQUEST_CLASS, REQUEST_STANDARD, REQUEST_TO_DEVICE, REQUEST_TO_INTERFACE, REQUEST_VENDOR, SetupPacket, USB_AltSetting, USB_ClrStallEP, USB_Configuration, USB_Configure_Event, USB_DataInStage, USB_DataOutStage, USB_DeviceAddress, USB_DirCtrlEP, USB_EVT_IN, USB_EVT_IN_STALL, USB_EVT_OUT, USB_EVT_OUT_STALL, USB_EVT_SETUP, USB_Feature_Event, USB_GetDescriptor, USB_GetStatus, USB_Interface_Event, USB_NumInterfaces, USB_REQUEST_CLEAR_FEATURE, USB_REQUEST_GET_CONFIGURATION, USB_REQUEST_GET_DESCRIPTOR, USB_REQUEST_GET_INTERFACE, USB_REQUEST_GET_STATUS, USB_REQUEST_SET_ADDRESS, USB_REQUEST_SET_CONFIGURATION, USB_REQUEST_SET_DESCRIPTOR, USB_REQUEST_SET_FEATURE, USB_REQUEST_SET_INTERFACE, USB_SetAddress, USB_SetClrFeature, USB_SetConfiguration, USB_SetInterface, USB_SetStallEP, USB_SetupStage, USB_StatusInStage, USB_StatusOutStage, VendorDataStage, VendorSetupStage.