.TH "_REQUEST_TYPE::_BM" 3 "Sun Oct 17 2010" "Version 01" "Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_REQUEST_TYPE::_BM \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <usb.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBRecipient\fP: 5"
.br
.ti -1c
.RI "\fBBYTE\fP \fBType\fP: 2"
.br
.ti -1c
.RI "\fBBYTE\fP \fBDir\fP: 1"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 47 of file usb.h.
.SH "Field Documentation"
.PP 
.SS "\fBBYTE\fP \fBDir\fP"
.PP
Definition at line 50 of file usb.h.
.SS "\fBBYTE\fP \fBRecipient\fP"
.PP
Definition at line 48 of file usb.h.
.SS "\fBBYTE\fP \fBType\fP"
.PP
Definition at line 49 of file usb.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware from the source code.
