.TH "_USB_DEVICE_DESCRIPTOR" 3 "Sun Oct 17 2010" "Version 01" "Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_USB_DEVICE_DESCRIPTOR \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <usb.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBbLength\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBbDescriptorType\fP"
.br
.ti -1c
.RI "\fBWORD\fP \fBbcdUSB\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBbDeviceClass\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBbDeviceSubClass\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBbDeviceProtocol\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBbMaxPacketSize0\fP"
.br
.ti -1c
.RI "\fBWORD\fP \fBidVendor\fP"
.br
.ti -1c
.RI "\fBWORD\fP \fBidProduct\fP"
.br
.ti -1c
.RI "\fBWORD\fP \fBbcdDevice\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBiManufacturer\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBiProduct\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBiSerialNumber\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBbNumConfigurations\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 142 of file usb.h.
.SH "Field Documentation"
.PP 
.SS "\fBWORD\fP \fBbcdDevice\fP"
.PP
Definition at line 152 of file usb.h.
.SS "\fBWORD\fP \fBbcdUSB\fP"
.PP
Definition at line 145 of file usb.h.
.SS "\fBBYTE\fP \fBbDescriptorType\fP"
.PP
Definition at line 144 of file usb.h.
.SS "\fBBYTE\fP \fBbDeviceClass\fP"
.PP
Definition at line 146 of file usb.h.
.SS "\fBBYTE\fP \fBbDeviceProtocol\fP"
.PP
Definition at line 148 of file usb.h.
.SS "\fBBYTE\fP \fBbDeviceSubClass\fP"
.PP
Definition at line 147 of file usb.h.
.SS "\fBBYTE\fP \fBbLength\fP"
.PP
Definition at line 143 of file usb.h.
.SS "\fBBYTE\fP \fBbMaxPacketSize0\fP"
.PP
Definition at line 149 of file usb.h.
.SS "\fBBYTE\fP \fBbNumConfigurations\fP"
.PP
Definition at line 156 of file usb.h.
.SS "\fBWORD\fP \fBidProduct\fP"
.PP
Definition at line 151 of file usb.h.
.SS "\fBWORD\fP \fBidVendor\fP"
.PP
Definition at line 150 of file usb.h.
.SS "\fBBYTE\fP \fBiManufacturer\fP"
.PP
Definition at line 153 of file usb.h.
.SS "\fBBYTE\fP \fBiProduct\fP"
.PP
Definition at line 154 of file usb.h.
.SS "\fBBYTE\fP \fBiSerialNumber\fP"
.PP
Definition at line 155 of file usb.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware from the source code.
