.TH "F:/MDBlue/CQ/NghienCuu/USBDongle/USBLPC/Release/Firmware/memory.c" 3 "Sun Oct 17 2010" "Version 01" "Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/MDBlue/CQ/NghienCuu/USBDongle/USBLPC/Release/Firmware/memory.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <LPC23xx.H>\fP
.br
\fC#include 'type.h'\fP
.br
\fC#include 'usb.h'\fP
.br
\fC#include 'usbcfg.h'\fP
.br
\fC#include 'usbhw.h'\fP
.br
\fC#include 'usbcore.h'\fP
.br
\fC#include 'memory.h'\fP
.br
\fC#include 'LCD.h'\fP
.br
\fC#include 'SerialLogger.h'\fP
.br
\fC#include 'Nhac.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBLED_Init\fP (void)"
.br
.ti -1c
.RI "void \fBLED_On\fP (unsigned int num)"
.br
.ti -1c
.RI "void \fBLED_Off\fP (unsigned int num)"
.br
.ti -1c
.RI "void \fBLED_Out\fP (unsigned int value)"
.br
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void LED_Init (void)"
.PP
Definition at line 29 of file memory.c.
.SS "void LED_Off (unsigned int num)"
.PP
Definition at line 41 of file memory.c.
.SS "void LED_On (unsigned int num)"
.PP
Definition at line 36 of file memory.c.
.SS "void LED_Out (unsigned int value)"
.PP
Definition at line 46 of file memory.c.
.SS "int main (void)"
.PP
Definition at line 53 of file memory.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware from the source code.
