.TH "F:/MDBlue/CQ/NghienCuu/USBDongle/USBLPC/Release/Firmware/memory.h" 3 "Sun Oct 17 2010" "Version 01" "Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/MDBlue/CQ/NghienCuu/USBDongle/USBLPC/Release/Firmware/memory.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBCCLK\fP   60000000"
.br
.ti -1c
.RI "#define \fBLED_MSK\fP   0x000000FF"
.br
.ti -1c
.RI "#define \fBLED_RD\fP   0x00000001"
.br
.ti -1c
.RI "#define \fBLED_WR\fP   0x00000002"
.br
.ti -1c
.RI "#define \fBLED_CFG\fP   0x00000010"
.br
.ti -1c
.RI "#define \fBLED_SUSP\fP   0x00000020"
.br
.ti -1c
.RI "#define \fBMSC_ImageSize\fP   0x00001000"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const unsigned char \fBDiskImage\fP [MSC_ImageSize]"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define CCLK   60000000"
.PP
Definition at line 14 of file memory.h.
.SS "#define LED_CFG   0x00000010"
.PP
Definition at line 20 of file memory.h.
.SS "#define LED_MSK   0x000000FF"
.PP
Definition at line 17 of file memory.h.
.SS "#define LED_RD   0x00000001"
.PP
Definition at line 18 of file memory.h.
.SS "#define LED_SUSP   0x00000020"
.PP
Definition at line 21 of file memory.h.
.SS "#define LED_WR   0x00000002"
.PP
Definition at line 19 of file memory.h.
.SS "#define MSC_ImageSize   0x00001000"
.PP
Definition at line 24 of file memory.h.
.SH "Variable Documentation"
.PP 
.SS "const unsigned char \fBDiskImage\fP[MSC_ImageSize]"
.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware from the source code.
