.TH "F:/MDBlue/CQ/NghienCuu/USBDongle/USBLPC/Release/Firmware/Nhac.h" 3 "Sun Oct 17 2010" "Version 01" "Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/MDBlue/CQ/NghienCuu/USBDongle/USBLPC/Release/Firmware/Nhac.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBInitSong\fP (void)"
.br
.ti -1c
.RI "void \fBNhacOn\fP (int iBaiHat)"
.br
.ti -1c
.RI "void \fBNhacOff\fP (void)"
.br
.ti -1c
.RI "void \fBNhacCustom\fP (void *p, int iLen)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void InitSong (void)"
.PP
Definition at line 99 of file Nhac.c.
.SS "void NhacCustom (void * p, int iLen)"
.PP
Definition at line 133 of file Nhac.c.
.SS "void NhacOff (void)"
.PP
Definition at line 126 of file Nhac.c.
.SS "void NhacOn (int iBaiHat)"
.PP
Definition at line 118 of file Nhac.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware from the source code.
