.TH "F:/MDBlue/CQ/NghienCuu/USBDongle/USBLPC/Release/Firmware/usbdesc.h" 3 "Sun Oct 17 2010" "Version 01" "Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/MDBlue/CQ/NghienCuu/USBDongle/USBLPC/Release/Firmware/usbdesc.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBWBVAL\fP(x)   (x & 0xFF),((x >> 8) & 0xFF)"
.br
.ti -1c
.RI "#define \fBUSB_DEVICE_DESC_SIZE\fP   (sizeof(\fBUSB_DEVICE_DESCRIPTOR\fP))"
.br
.ti -1c
.RI "#define \fBUSB_CONFIGUARTION_DESC_SIZE\fP   (sizeof(\fBUSB_CONFIGURATION_DESCRIPTOR\fP))"
.br
.ti -1c
.RI "#define \fBUSB_INTERFACE_DESC_SIZE\fP   (sizeof(\fBUSB_INTERFACE_DESCRIPTOR\fP))"
.br
.ti -1c
.RI "#define \fBUSB_ENDPOINT_DESC_SIZE\fP   (sizeof(\fBUSB_ENDPOINT_DESCRIPTOR\fP))"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBBYTE\fP \fBUSB_DeviceDescriptor\fP []"
.br
.ti -1c
.RI "const \fBBYTE\fP \fBUSB_ConfigDescriptor\fP []"
.br
.ti -1c
.RI "const \fBBYTE\fP \fBUSB_StringDescriptor\fP []"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define USB_CONFIGUARTION_DESC_SIZE   (sizeof(\fBUSB_CONFIGURATION_DESCRIPTOR\fP))"
.PP
Definition at line 23 of file usbdesc.h.
.SS "#define USB_DEVICE_DESC_SIZE   (sizeof(\fBUSB_DEVICE_DESCRIPTOR\fP))"
.PP
Definition at line 22 of file usbdesc.h.
.SS "#define USB_ENDPOINT_DESC_SIZE   (sizeof(\fBUSB_ENDPOINT_DESCRIPTOR\fP))"
.PP
Definition at line 25 of file usbdesc.h.
.SS "#define USB_INTERFACE_DESC_SIZE   (sizeof(\fBUSB_INTERFACE_DESCRIPTOR\fP))"
.PP
Definition at line 24 of file usbdesc.h.
.SS "#define WBVAL(x)   (x & 0xFF),((x >> 8) & 0xFF)"
.PP
Definition at line 20 of file usbdesc.h.
.SH "Variable Documentation"
.PP 
.SS "const \fBBYTE\fP \fBUSB_ConfigDescriptor\fP[]"
.PP
Definition at line 58 of file usbdesc.c.
.SS "const \fBBYTE\fP \fBUSB_DeviceDescriptor\fP[]"
.PP
Definition at line 39 of file usbdesc.c.
.SS "const \fBBYTE\fP \fBUSB_StringDescriptor\fP[]"
.PP
Definition at line 117 of file usbdesc.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware from the source code.
